var arrLang = {
    "en": {
      "HOME": "Home",
      "ABOUT": "About me",
      "KNOWLEDGES":"Technical knowledge",
      "RESUME":"Resume",
      "PORTFOLIO":"Portfolio",
      "COURSES":"Courses",
      "LANGUAGES":"Languages",
      "SKILLS":"Skills",
      "CONTACT": "Contact",
      "BIRTHDAY":"Birthdate:",
      "CITY":"City:",
      "NATIONALITY":"Nationality:",
      "AGE":"Age:",
      "DEGREE":"Degree:",
      "ABOUT-DESCRIPTION":"I'm bioengineer graduated, currently working in web development with three years of professional experience. I've always been interested in understanding how the web works, regardless of the known languages and ever looking for the integration of concepts. This search has led me to learn about the history of the web, the data send from and to the server, the refresh of pages, the meaning of Single Page Application, the importance of the introduction of AJAX in browsers, the role of Apis y endpoints in the modern web. I've always believed that the programming language is like a tool in the development, and therefore it's more useful to know these concepts correctly before any development. I'm mainly interested at backend, although I also work with frontend currently. In my current job, I use codeigniter 3, Jquery, PostgreSQL and VueJS, with a lot of use of the developer tools of the browsers, where I use console, network, sources, elements and application tabs. Focused on continuos formation, I'm seeking to learn new technologies. Nowdays, I'm learning about microservices concepts, using Serverless with Vercel and NextJS or lambda functions in AWS",
      "BIOENGINEER":"Bioengineer",
      "MILESTONES":"Milestones",
      "MILESTONES-DESCRIPTION":"Some numbers about achieved achievements",
      "COURSES":"Courses and certificates",
      "PROJECTS":"Professional projects",
      "PROGRAMMING-HOURS":"Programming hours",
      "PROGRAMMING-YEARS":"Years in software development",
      "AWARDS":"Awards and honours",
      "MVC":"Design pattern model view controller",
      "ARQ-TYPE":"Monolitics and serverless app",
      "FRAMEWORKS-LIBRARIES":"Frameworks and libraries",
      "API-CREATION":"Modeling and creation of Application programming interfaces (APIs)",
      "SESSION-MANIPULATION":"Session manipulation",
      "USER-CONTROL":"User control with JSON web tokens",
      "API-CONSUMO":"API consumpion",
      "SQL":"Structured Query Language(SQL) usage",
      "DATABASE":"Databases",
      "AUTHORIZATION-AND-AUTENTICATION":"Authorization and authentication",
      "ENCRIPTATION":"Encription and hash of data",
      "DATABASE-RELATIONAL-NO-RELATIONAL":"Relational and no relational databases",
      "PROFESSIONAL-USE":"Professional usage",
      "APRENDIZAJE":"Learning",
      "INTERMEDIO":"Intermediate",
      "LAMBDA-FUNCTIONS":"Lambda functions",
      "VERCEL-FUNCTIONS":"Vercel functions",
      "MYSQL-DATABASE":"MySql database",
      "POSTGRES-DATABASE":"Postgresql database",
      "MONGO-DATABASE":"Mongo database",
      "TECHNOLOGIES":"Technologies",
      "SSR-CSR":"Server side rendering(SSR) and Client side rendering(CSR)",
      "SITE-TYPE":"Browser opration: Static sites vs dynamic sites",
      "AJAX":"Knowledge and use of Asynchronous JavaScript and XML(AJAX)",
      "SPA":"Single Page Application(SPA)",
      "TOOLS-BROWSER":"Browser developer tools: Use of console, network, elements, styles, application tabs",
      "STYLES":"Styles",
      "DOM":"Knowledge and manipulation of Document Object Model(DOM) and virtual DOM",
      "COMPUTATION":"Computation and informatics",
      "OS":"Operative System knowledge and comprehension",
      "PORT-ASSIGNATION":"Port assignation",
      "SERVICES":"Operation of services and processes",
      "LAN-INTERNET":"Local Area Network and Internet",
      "MIGRATION":"Migrations",
      "RESUME":"Resume",
      "SUMMARY":"Summary",
      "SHORT-DESCRIPTION":"Software developer with two years of professional experiencie. Full stack tasks although I'm more interested on the Backend.",
      "BIOENGINEER":"Bioengineer",
      "EDUCATION":"Education",
      "TITLE-DESCRIPTION":"Bachelor in Bioengineering. Excellent performance in maths and informatics. Average: 8.14/10",
      "PROFESSIONAL-EXPERIENCE":"Professional experience",
      "CURRENT":"Current",
      "VISUAL-DESCRIPTION":"Web developer in company focused on medical imaging technology",
      "DESARROLLO":"Development and maintenance tasks",
      "NEW-DESARROLLO":"New developments, fix of bugs, permanent participation on new developments giving opinions",
      "MAIN-SYSTEMS":"Main systems mades in Codeigniter 3 and Jquery with PostgreSQL",
      "CODE4":"Update to Codeigniter 4 in some systems",
      "VISUAL-SOCIAL":"Making new development on NodeJS with ExpressJS using MongoDB",
      "SYSTEM-COMUNICATION":"Communications between the systems",
      "USED-TECHNOLOGIES":"Used technologies",
      "MEDICOR-JOB":"Technical assistant in Neurosurgeries",
      "WEB-CALENDAR":"Web App type calendar made for the company to track the surgeries of the company using Php, MySql, Bootstrap",
      "MATERIALES-MEDICOR":"Provision of services and materials in neurosurgeries",
      "SURGERY-PLAN":"Neuronavigation planning, approach and use during surgery",
      "SURGERY-ASSISTANCE":"Assistance to surgery by providing ultrasonic aspirator, craniotome and closure materials",
      "PORTFOLIO-DESCRIPTION":"some projects that I have carried out, whether as course completions, job proposals, professional environment or entertainment",
      "COURSES-DESCRIPTION":"Extra training that has served for continuous updating",
      "ATM":"ATM Simulator",
      "WEB-SURGERIES":"Web App sort calendar to track the surgeries of a company",
      "WEATHER-APP":"App that allows know the weather in any city",
      "REST-SERVER-MODEL":"Rest Server Model",
      "PWA":"Little PWA",
      "COMMENTARIES":"App with AMD of users and commentaries",
      "BOLETA-UNICA-SIMULATOR":"Simulator of elections ticket",
      "FOOTBALL-SIMULATOR":"Simulator of football tournament",
      "COMPUTER-AIDED-DIAGNOSES":"Computer Aided Diagnoses",
      "FFT":"Fourier Transform",
      "BUGS-SOLUTIONS":"Solutions to bugs",
      "JAVA-ORACLE":"Java Intermediate Oracle Sun",
      "ACADEMIAS-UTN":"UTN Academy Mendoza",
      "NODE-CERO":"Node: From zero to expert (Edition 2021)",
      "JS-ES6":"Learn Javascript ES6, HTML, CSS3 and NodeJS from zero",
      "JS-CERO":"Javascript: From zero to details (ES5)",
      "PHP-MYSQL":"Course Php/MySql",
      "PYTHON-CERO":"Course Python from zero",
      "SPOKEN-LANGUAGES":"Languages",
      "SPANISH":"Spanish",
      "NATIVE":"Native",
      "ENGLISH":"English",
      "B2-LEVEL":"B2 Level",
      "CUI-LEVEL":"Level 8 B1.2",
      "FROM-TO-CUI":"January - March 2023",
      "FROM-TO-COUNCIL":"May - August 2023",
      "TEMPORAL-ESTIMATION-DESCRIPTION":"Good ability to estimate the appropriateness of task durations",
      "VERSIONS-DESCRIPTION":"Interpretation and appropriate management of versions, releases and hot fixes",
      "MULTI-GROUPS-DESCRIPTION":"Ability to carry out tasks jointly with a team, differentiating tasks and stipulating times to achieve a joint goal",
      "SELF-WORKER-DESCRIPTION":"Ability to perform tasks individually",
      "LEARNING-DESCRIPTION":"Continuous interest in keeping knowledge up to date by seeking the latest technologies used",
      "ADAPTATION-DESCRIPTION":"Ability to positively face changes",
      "ADAPTATION":"Adaptation",
      "LEARNING":"Learning",
      "SELF-WORKER":"Work individually",
      "MULTI-GROUPS":"Work in multidisciplinary groups",
      "VERSIONS":"Versioned",
      "TEMPORAL-ESTIMATION":"Temporary estimates",
      "ADRESS":"Adress",
      "SENT-MESSAGE":"Your message has been sent",
      "SEND-MESSAGE":"Send Message",
      "FOOTER-DESCRIPTION":"Don't hesitate to contact me with any questions.",
      "LOADING":"Loading",
      "NAMEMAIL":"Name",
      "emailMail":"Email",
      "asuntoMail":"Subject",
      "mensajeMail":"Message",
      "LEARN-REACT":"Learn React",
      "PRODE-SIMULATOR":"Prode simulator",
      "WHEATHER-APP": "Wheather App",
      "FLAGS-GAME":"Flags game",
      "FETCHING-DATA":"Fetching data from a server",
      "DIPLOMATURE-BBDD":"Database Diplomature",
    },
    "es": {
      "HOME": "Inicio",
      "ABOUT": "Acerca de mi",
      "KNOWLEDGES":"Conocimientos técnicos",
      "RESUME":"Currículum",
      "PORTFOLIO":"Portfolio",
      "COURSES":"Cursos",
      "LANGUAGES":"Idiomas",
      "SKILLS":"Habilidades",
      "CONTACT": "Contacto",
      "BIRTHDAY":"Fecha de nacimiento:",
      "CITY":"Ciudad:",
      "NATIONALITY":"Nacionalidad:",
      "AGE":"Edad:",
      "DEGREE":"Título:",
      "ABOUT-DESCRIPTION":"Bioingeniero trabajando en el campo del desarrollo web, con tres años de experiencia profesional. Al margen de los lenguajes conocidos, siempre estuve interesado en comprender el funcionamiento de la web, buscando la integración de conceptos. Esta búsqueda de integración me llevó a aprender de la historia de la web, los conceptos de envío de datos al servidor y refresco de páginas, el significado de Single Page Application, la importancia de la introducción de AJAX en los navegadores, el rol fundamental de las Apis y endpoints en la web moderna. Siempre creí que el lenguaje de programación es en realidad una herramienta, y que es más importante conocer correctamente estos conceptos antes de cualquier desarrollo. Interesado principalmente en backend, aunque en actualidad también trabajo con frontend. En empleo actual hago uso de codeigniter 3, Jquery, PostgreSQL y VueJS, con mucho de uso de las herramientas de desarrollador de los navegadores, donde utilizo las pestañas de consola, los elementos de red, las fuentes, los elementos, la aplicación. Siempre apuntando a la formación continua, busco aprender nuevas tecnologías. Hoy en día estoy aprendiendo conceptos de microservicios, haciendo uso de Serverless con Vercel usando NextJS o funciones Lambda en AWS",
      "BIOENGINEER":"Bioingeniero",
      "MILESTONES":"Hitos",
      "MILESTONES-DESCRIPTION":"Algunos números sobre logros alcanzados",
      "COURSES":"Cursos y certificados",
      "PROJECTS":"Proyectos profesionales",
      "PROGRAMMING-HOURS":"Horas de programación",
      "PROGRAMMING-YEARS":"Años en desarrollo de software",
      "AWARDS":"Premios y reconocimientos",
      "MVC":"Patrón de diseño modelo vista controlador",
      "ARQ-TYPE":"Aplicaciones monolíticas y serverless",
      "FRAMEWORKS-LIBRARIES":"Frameworks and librarias",
      "API-CREATION":"Modelado y creación de Application Programming Interfaces (API)",
      "SESSION-MANIPULATION":"Manipulación de sesiones",
      "USER-CONTROL":"Control de usuarios con JSON Web Tokens(JWT)",
      "API-CONSUMO":"Consumo de APIs",
      "SQL":"Uso de Structured Query Language(SQL)",
      "DATABASE":"Base de datos",
      "AUTHORIZATION-AND-AUTENTICATION":"Autorización y autenticación",
      "ENCRIPTATION":"Encriptation y hasheado de datos",
      "DATABASE-RELATIONAL-NO-RELATIONAL":"Base de datos relacionales y no relacionales",
      "PROFESSIONAL-USE":"Uso profesional",
      "APRENDIZAJE":"En aprendizaje",
      "INTERMEDIO":"Intermedio",
      "LAMBDA-FUNCTIONS":"Funciones Lambda",
      "VERCEL-FUNCTIONS":"Funciones Vercel",
      "MYSQL-DATABASE":"Base de datos MySql",
      "POSTGRES-DATABASE":"Basde de datos Postgresql",
      "MONGO-DATABASE":"Base de datos Mongo",
      "TECHNOLOGIES":"Tecnologías",
      "SSR-CSR":"Renderizado del lado del servidor(SSR) y del lado del cliente(CSR)",
      "SITE-TYPE":"Interpretación de funcionamiento de un navegador: sitios estáticos vs dinámicos",
      "AJAX":"Conocimiento de significado de Asynchronous Javascript and XML y su funcionamiento",
      "SPA":"Aplicaciones de una sola página(SPA)",
      "TOOLS-BROWSER":"Herramientas de desarrollo de los navegadores: uso de pestañas de consola, red, elementos, estilos, aplicación",
      "STYLES":"Estilos",
      "DOM":"Conocimiento y manipulación de Document Object Model(DOM) y DOM virtual",
      "COMPUTATION":"Computación e informática",
      "OS":"Comprensión de funcionamiento de los sistemas operativos",
      "PORT-ASSIGNATION":"Asignación de puertos",
      "SERVICES":"Funcionamiento de servicios y procesos",
      "LAN-INTERNET":"Redes locales e internet",
      "MIGRATION":"Migraciones",
      "RESUME":"Currículum Vitae",
      "SUMMARY":"Resumen",
      "SHORT-DESCRIPTION":"Software developer con dos años de experiencia profesional. Tareas full-stack aunque presento mayor interés por el back-end.",
      "BIOENGINEER":"Bioingeniería",
      "EDUCATION":"Educación",
      "TITLE-DESCRIPTION":"Carrera de grado. Excelente desempeño en materias matemáticas e informáticas. Promedio académico: 8.14/10",
      "PROFESSIONAL-EXPERIENCE":"Experiencia profesional",
      "CURRENT":"Presente",
      "VISUAL-DESCRIPTION":"Web developer en empresa orientada a tecnología en imagen médica",
      "DESARROLLO":"Tareas de desarrollo y mantenimiento",
      "NEW-DESARROLLO":"Nuevos desarrollos, fix de bugs, permanente participación en nuevos desarrollos aportando ideas",
      "MAIN-SYSTEMS":"Sistemas principales desarrollados en Codeigniter 3 y Jquery usando PostgreSQL",
      "CODE4":"Actualización a Codeigniter 4 de algunos sistemas",
      "VISUAL-SOCIAL":"Nuevo desarrollo actual realizando en NodeJS con ExpressJS usando MongoDB",
      "SYSTEM-COMUNICATION":"Comunicación entre los sistemas",
      "USED-TECHNOLOGIES":"Tecnologías usadas",
      "MEDICOR-JOB":"Asistente técnico en servicios de Neurocirugía",
      "WEB-CALENDAR":"Realizado de aplicación tipo calendario para controlar cirugías de la empresa usando Php, MySql, Bootstrap",
      "MATERIALES-MEDICOR":"Prestación de servicios y materiales en neurocirugías",
      "SURGERY-PLAN":"Planificación de neuronavegación, abordaje y utilización durante la cirugía",
      "SURGERY-ASSISTANCE":"Asistencia a cirugía prestando aspirador ultrasónico, craneótomo y materiales de cierre",
      "PORTFOLIO-DESCRIPTION":"Algunos proyectos que he desarrollado, ya sea como finalizaciones de cursos, propuestas laborales, entorno profesional o entretenimiento",
      "COURSES-DESCRIPTION":"Capacitaciones extras que han servido para la actualización continua",
      "ATM":"Simulador Cajero automático",
      "ATM":"Simulador de Cajero Automático",
      "WEB-SURGERIES":"Web App tipo calendario para controlar insumos y servicios de una empresa",
      "WEATHER-APP":"App que permite conocer el clima en distintas ciudades",
      "REST-SERVER-MODEL":"Modelo Rest Server",
      "PWA":"Pequeña PWA",
      "COMMENTARIES":"App con ABM para usuarios y comentarios",
      "BOLETA-UNICA-SIMULATOR":"Simulador de Boleta Única",
      "FOOTBALL-SIMULATOR":"Simulador de torneo de fútbol",
      "COMPUTER-AIDED-DIAGNOSES":"Computer Aided Diagnoses",
      "FFT":"App que permite calcular la Tranformada de Fourier",
      "BUGS-SOLUTIONS":"Soluciones a bugs",
      "JAVA-ORACLE":"Java Intermedio Oracle Sun",
      "ACADEMIAS-UTN":"Academias UTN Mendoza",
      "NODE-CERO":"Node: De cero a experto (Edición 2021)",
      "JS-ES6":"Aprende Javascript ES6, HTML, CSS3 y NodeJS desde cero",
      "JS-CERO":"Javascript: de cero hasta los detalles (ES5)",
      "PHP-MYSQL":"Curso Php/MySql",
      "PYTHON-CERO":"Curso Python desde 0.",
      "SPOKEN-LANGUAGES":"Idiomas",
      "SPANISH":"Español",
      "NATIVE":"Nativo",
      "ENGLISH":"Inglés",
      "B2-LEVEL":"Nivel B2",
      "CUI-LEVEL":"Nivel 8 B1.2",
      "FROM-TO-CUI":"Enero - Marzo 2023",
      "FROM-TO-COUNCIL":"Mayo - Agosto 2023",
      "TEMPORAL-ESTIMATION-DESCRIPTION":"Buena habilidad para calcular de manera apropiada los tiempos de tareas",
      "VERSIONS-DESCRIPTION":"Interpretación y manejo apropiado de versiones, liberados y hot fixs",
      "MULTI-GROUPS-DESCRIPTION":"Habilidad para realizar tareas de manera conjunta con un equipo, diferenciando tareas y estipulando tiempos para alcanzar una meta conjunta",
      "SELF-WORKER-DESCRIPTION":"Habilidad para afrontar tareas de manera individual",
      "LEARNING-DESCRIPTION":"Continuo interés por mantener los conocimientos al día buscando las últimas tecnologías usadas",
      "ADAPTATION-DESCRIPTION":"Capacidad para afrontar de manera positiva cambios",
      "ADAPTATION":"Adaptación",
      "LEARNING":"Aprendizaje",
      "SELF-WORKER":"Trabajo de manera individual",
      "MULTI-GROUPS":"Trabajo en grupos multidisciplinarios",
      "VERSIONS":"Versionados",
      "TEMPORAL-ESTIMATION":"Estimaciones temporales",
      "ADRESS":"Dirección",
      "SENT-MESSAGE":"Tu mensaje ha sido enviado",
      "SEND-MESSAGE":"Enviar mensaje",
      "FOOTER-DESCRIPTION":"No dudes en contactarme ante cualquier inquietud",
      "LOADING":"Cargando",
      "NAMEMAIL":"Nombre",
      "emailMail":"Email",
      "asuntoMail":"Asunto",
      "mensajeMail":"Mensaje",
      "LEARN-REACT":"Aprende react",
      "PRODE-SIMULATOR":"Simulador de Prode",
      "WHEATHER-APP": "Aplicación para conocer el clima",
      "FLAGS-GAME":"Juego para adivinar banderas",
      "FETCHING-DATA":"Obteniendo data del servidor",
      "DIPLOMATURE-BBDD":"Diplomatura en base de datos",
    }}

  $(document).ready(function() {
    // The default language is English
    var lang = navigator.language.slice(0,2);
    $(".lang").each(function(index, element) {
      $(this).text(arrLang[lang][$(this).attr("key")]);
    });
  });

  // get/set the selected language
  $(".translate").click(function() {
    var lang = $(this).attr("id");

    $(".lang").each(function(index, element) {
      $(this).text(arrLang[lang][$(this).attr("key")]);
    });
  });
